elasticsearch:
  host: http://localhost
  port: 9200
  username: Mohammad
  password: mohammad.s1381

logger:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO

embedding:
  model_names: ["all-MiniLM-L6-v2", "bert-base-nli-mean-tokens", "roberta-base-nli-stsb-mean-tokens"]
